- name: 'License'
  shield: 'https://img.shields.io/badge/license-CC%20BY--NC%204.0-blue.svg'
  url: 'https://creativecommons.org/licenses/by-nc/4.0/'
- name: 'Vite'
  shield: 'https://img.shields.io/badge/vite-^7.2.4-blue.svg'
  url: 'https://vitejs.dev/'
- name: 'TypeScript'
  shield: 'https://img.shields.io/badge/typescript-^6.0.0--beta-blue.svg'
  url: 'https://www.typescriptlang.org/'
- name: 'Tailwind CSS'
  shield: 'https://img.shields.io/badge/tailwind%20css-^4.1.18-blue.svg'
  url: 'https://tailwindcss.com/'
- name: 'React'
  shield: 'https://img.shields.io/badge/react-^19.2.3-blue.svg'
  url: 'https://reactjs.org/'
- name: 'Biome'
  shield: 'https://img.shields.io/badge/biome-^1.8.3-blue.svg'
  url: 'https://biomejs.dev/'
